###############################################################################
#                           Authelia Configuration                           #
###############################################################################

# The host and port to listen on
server:
  host: 0.0.0.0
  port: 9091

# Level of verbosity for logs: debug, info, warn, error
log:
  level: info
  format: text
  file_path: ""

# Default redirection URL
default_redirection_url: https://auth.yourdomain.com

# TOTP settings
totp:
  issuer: YourHomeLab
  period: 30
  skew: 1

# WebAuthn settings (security keys)
webauthn:
  disable: false
  display_name: YourHomeLab
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s

# Set domains on which cookies will be set
# Should match your root protected domain
session:
  name: authelia_session
  domain: yourdomain.com
  same_site: lax
  expiration: 3600  # 1 hour
  inactivity: 300   # 5 minutes
  remember_me_duration: 2592000  # 30 days
  
  # Configure Redis for session storage (recommended)
  # Uncomment and configure to use Redis instead of memory
  redis:
    host: redis
    port: 6379
    password: RedisPasswordChangeMe
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 2

# Database settings (using local file)
storage:
  local:
    path: /config/db.sqlite3
  
  # MySQL/MariaDB example (for production)
  # mysql:
  #  host: mariadb
  #  port: 3306
  #  database: authelia
  #  username: authelia
  #  password: authelia_password

# Authentication backends
authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

  # LDAP example (for production)
  # ldap:
  #   url: ldap://openldap
  #   start_tls: false
  #   base_dn: dc=example,dc=com
  #   username_attribute: uid
  #   additional_users_dn: ou=users
  #   users_filter: (&({username_attribute}={input})(objectClass=person))
  #   additional_groups_dn: ou=groups
  #   groups_filter: (&(member={dn})(objectClass=groupOfNames))
  #   group_name_attribute: cn
  #   mail_attribute: mail
  #   display_name_attribute: displayName

# Access control settings
access_control:
  default_policy: deny
  
  # Rules for accessing protected resources
  rules:
    # Public endpoints - no authentication required
    - domain: public.yourdomain.com
      policy: bypass
    
    # Admin endpoints - require 2FA
    - domain: 
        - admin.yourdomain.com
        - grafana.yourdomain.com
        - prometheus.yourdomain.com
      policy: two_factor
      subject:
        - "group:admins"
    
    # Regular services - require single factor
    - domain: "*.yourdomain.com"
      policy: one_factor
      subject:
        - "group:users"

# Notification settings for password reset
notifier:
  # Use file-based notifications for testing (emails written to file)
  filesystem:
    filename: /config/notification.txt
  
  # For production, configure SMTP
  # smtp:
  #   host: smtp.example.com
  #   port: 587
  #   timeout: 5s
  #   username: authelia@example.com
  #   password: mypassword
  #   sender: authelia@example.com
  #   identifier: localhost
  #   subject: "[Authelia] {title}"
  #   startup_check_address: test@example.com
  #   disable_require_tls: false
  #   disable_html_emails: false
  #   tls:
  #     skip_verify: false
  #     minimum_version: TLS1.2

# Settings for the Authelia portal
theme: dark

# Regulations for failed authentications
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

# Secrets are managed via environment variables