global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Example job for monitoring Docker Host
  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Pi-hole monitoring (if available)
  - job_name: "pihole"
    scrape_interval: 60s
    static_configs:
      - targets: ["pihole:9617"]

  # Traefik monitoring (if available)
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8082"]
    
  # Add more targets as needed for your homelab services