name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Lint
      run: |
        if [ -f "package.json" ] && grep -q "\"lint\"" "package.json"; then
          npm run lint
        else
          echo "Linting not configured, skipping..."
        fi
        
    - name: Test
      run: |
        if [ -f "package.json" ] && grep -q "\"test\"" "package.json"; then
          npm run test
        else
          echo "Tests not configured, skipping..."
        fi
        
    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          dist
          build
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-